<?php
namespace app\controllers;

class IndexController extends BaseController {

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex() {
//        $this->layout = true;
        return $this->render('index');
    }
}