<?php
namespace app\controllers;

use yii\web\Controller;
class UserController extends BaseController {

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub\

    }

    public function actionIndex() {
        $this->layout = false;
        return $this->render('login');
    }
    public function actionLogin() {
        $post = $this->getPost();
        print_r($post);die;
    }
}